name: 'Nix provenance'
description: 'Nix provence from flake'
inputs:
  flakeref:
    description: 'The nix flake'
    required: true
outputs:
  provenance:
    description: "Provenance path"
    value: ${{ steps.provenance.outputs.provenance }}
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/main.py flakeref
      shell: bash
    - run: cat ${{ github.action_path }}/provenance.py | jq .
      shell: bash
    - id: provenance
      run: echo "provenance=${{ github.action_path }}/provenance.json" >> $GITHUB_OUTPUT
      shell: bash
