name: 'Nix provenance'
description: 'Nix provence from flake'
inputs:
  flakeref:
    description: 'The nix flake'
    required: true
outputs:
  provenance:
    description: "Provenance path"
    value: ${{ steps.provenance.outputs.provenance }}
runs:
  using: "composite"
  steps:
    - run: env
      shell: bash
    - run: python ${{ github.action_path }}/main.py ${{ inputs.flakeref }} --out /tmp/provenance.json
      shell: bash
    - run: cat /tmp//provenance.py | jq .
      shell: bash
    - id: provenance
      run: echo "provenance=/tmp/provenance.json" >> $GITHUB_OUTPUT
      shell: bash
