name: Nix build with provenance

inputs:
  target:
    description: The nix target to build
    required: true
  build-args:
    description: arguments given to nix build 
    required: false
  install-nix:
    required: false
    default: 'true'

outputs:
  provenance:
    description: Provenance path
    value: ${{ steps.provenance.outputs.provenance }}

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v22
      if: inputs.install-nix == 'true'
   
    - id: timestamp-begin
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
      shell: bash

    - id: build
      run: nix build ${{ inputs.target }} ${{ inputs.build-args }}
      shell: bash

    - id: timestamp-end
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
      shell: bash

    - run: nix run github:tiiuae/sbomnix#provenance ${{ inputs.target }}
      shell: bash
      env:
        PROVENANCE_OUTPUT_FILE: /tmp/provenance.json
        PROVENANCE_TIMESTAMP_BEGIN: ${{ steps.timestamp-begin.outputs.timestamp }}
        PROVENANCE_TIMESTAMP_FINISHED: ${{ steps.timestamp-end.outputs.timestamp }}
        PROVENANCE_EXTERNAL_PARAMS: ${{ toJson(inputs) }}
        PROVENANCE_INTERNAL_PARAMS: ${{ toJson(github) }}
        PROVENANCE_INVOCATION_ID: ${{ github.run_number }}
        PROVENANCE_BUILDER_ID: "https://github.com/actions/runner/github-hosted" 
        PROVENANCE_BUILD_TYPE: "https://github.com/Attestations/GitHubActionsWorkflow@v1"

    - id: provenance
      run: echo "provenance=/tmp/provenance.json" >> $GITHUB_OUTPUT
      shell: bash
