name: Nix provenance

inputs:
  target:
    description: Nix flake or derivation
    required: true

outputs:
  provenance:
    description: Provenance path
    value: ${{ steps.provenance.outputs.provenance }}

runs:
  using: composite
  steps:
    - run: python ${{ github.action_path }}/../src/main.py ${{ inputs.target }}
      shell: bash
      env:
        PROVENANCE_OUTPUT_FILE: /tmp/provenance.json

    - id: provenance
      run: echo "provenance=/tmp/provenance.json" >> $GITHUB_OUTPUT
      shell: bash
