name: "Build with provenance"
on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: ./nix-build-with-provenance.sh
      env:
        PROVENANCE_INVOCATION_ID: ${{ github.run_number }}
        PROVENANCE_BUILDER_ID: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
        PROVENANCE_BUILD_TYPE: TBD
